version: "3.0"
services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - '5673:5673'
      # HTTP management UI
      - '15673:15673'

# https://www.section.io/engineering-education/dockerize-a-rabbitmq-instance/ The code for the direct from this article