INSERT INTO KAPOLLER(FIRSTNAME, LASTNAME, PASSWORD, USERNAME) VALUES ('Ole', 'Rebnor', 'IyL22kSY0s#X', 'Ole_R' );
INSERT INTO KAPOLLER(FIRSTNAME, LASTNAME, PASSWORD, USERNAME) VALUES ('Dole', 'Rebnor', 'PP24732SY0s!X', 'Dole_R' );
INSERT INTO KAPOLLER(FIRSTNAME, LASTNAME, PASSWORD, USERNAME) VALUES ('Doffen', 'Rebnor', 'OldqaSY0s#X', 'Doffen_R' );
INSERT INTO KAPOLLER(FIRSTNAME, LASTNAME, PASSWORD, USERNAME) VALUES ('Hans', 'Vestmann', '+I@tkxuYZJyR&$@g#X', 'Vestmann_Hans');

INSERT INTO POLL(QUESTION, TIME, TITLE, OWNER, VOTE_VOTER_ID) VALUES ('Are pancakes better than waffles', 100, 'Pancakes vs waffles', 101, 1);
INSERT INTO VOTERS(POLL_ID, VOTE) VALUES (102, 1);
INSERT INTO POLL(QUESTION, TIME, TITLE, OWNER, VOTE_VOTER_ID) VALUES ('Are crepes better than waffles', 100, 'Crepes vs waffles', 101, 101);
INSERT INTO VOTERS(POLL_ID, VOTE) VALUES (101, 1);

INSERT INTO POLL_RESULT(NOVOTE, UTILDATE, YESVOTE) VALUES (1,'2022-12-23 13:10:11',0 );
